blank_issues_enabled: false
contact_links:
  - name: Report a Code of Conduct violation
    url: https://code-of-conduct.openjsf.org/
    about: "Do you want to report a Code of Conduct violation?"
  - name: Legal Help
    url: https://github.com/openjs-foundation/cross-project-council#help-with-legal-questions-for-existing-projects-only
    about: "Do you need help with legal matters concerning an OpenJSF project?"
  - name: Infrastructure Request
    url: https://github.com/openjs-foundation/cross-project-council#help-with-lf-it-supported-infrastructure
    about: "Do you want to request infrastructure resources for your OpenJSF project?"
