blank_issues_enabled: false
contact_links:
  - name: Report a Code of Conduct violation
    url: https://code-of-conduct.openjsf.org/
  - name: Legal Help
    url: https://github.com/openjs-foundation/cross-project-council#help-with-legal-questions-for-existing-projects-only
    about: "Do you need help with legal matters?"
  - name: Infrastructure Request
    url: https://github.com/openjs-foundation/cross-project-council#help-with-project-infrastructure
    about: "Do you want to request infrastructure resources?"
